
/** 
* THIS FILE IS GENERATED BY THE SCRIPT generate-inputs
* DO NOT EDIT THIS FILE DIRECTLY, ANY CHANGES WILL BE OVERWRITTEN
*
* @generated on 2022-08-10T22:03:44.032Z 
* 
*/
  
import { Prisma } from '@prisma/client';

export type Stream = {
  id: string
  streamId: number
  sender: string
  recipient: string
  tokenAddress: string
  deposit: number
  startTime: Date
  stopTime: Date
  createdAt: Date
  updatedAt: Date
}

export type WithdrawFromStream = {
  id: string
  streamId: string
  recipient: string
  amount: number
  createdAt: Date
  updatedAt: Date
}

export type GeneratedEntities = {stream:Stream,withdrawFromStream:WithdrawFromStream}
export type GeneratedCreateInputs = {stream:Prisma.StreamCreateInput,withdrawFromStream:Prisma.WithdrawFromStreamCreateInput}
export type GeneratedWhereInputs = {stream:Prisma.StreamWhereInput,withdrawFromStream:Prisma.WithdrawFromStreamWhereInput}
export type GeneratedUpdateInputs = {stream:Prisma.StreamUpdateInput,withdrawFromStream:Prisma.WithdrawFromStreamUpdateInput}
export type GeneratedSelects = {stream:Prisma.StreamSelect,withdrawFromStream:Prisma.WithdrawFromStreamSelect}