
/** 
* ================================================================== 
* This file is generated by script 'gen-inputs'                     |
* Do not edit this file directly, any changes will be overwritten   |
* ==================================================================
* @generated on 2022-08-18T20:28:11.425Z 
* 
*/
  
import { Prisma, Stream, WithdrawFromStream, TransactionBlockStatus } from '@prisma/client';

export type GeneratedEntities = {stream:Stream,withdrawFromStream:WithdrawFromStream,transactionBlockStatus:TransactionBlockStatus}
export type GeneratedCreateInputs = {stream:Prisma.StreamCreateInput,withdrawFromStream:Prisma.WithdrawFromStreamCreateInput,transactionBlockStatus:Prisma.TransactionBlockStatusCreateInput}
export type GeneratedWhereInputs = {stream:Prisma.StreamWhereInput,withdrawFromStream:Prisma.WithdrawFromStreamWhereInput,transactionBlockStatus:Prisma.TransactionBlockStatusWhereInput}
export type GeneratedUpdateInputs = {stream:Prisma.StreamUpdateInput,withdrawFromStream:Prisma.WithdrawFromStreamUpdateInput,transactionBlockStatus:Prisma.TransactionBlockStatusUpdateInput}
export type GeneratedSelects = {stream:Prisma.StreamSelect,withdrawFromStream:Prisma.WithdrawFromStreamSelect,transactionBlockStatus:Prisma.TransactionBlockStatusSelect}