import { writeFileSync, readFileSync } from 'fs';
import * as path from 'path';

function writeOnFile({ path, content }: { path: string; content: string }) {
  writeFileSync(
    path,
    `
     /**
   * ==================================================================
   * This file is generated by script 'gen-inputs'                     |
   * Do not edit this file directly, any changes will be overwritten   |
   * ==================================================================
   * @generated on ${new Date().toISOString()}
   */
  \n${content}`,
    {
      encoding: 'utf8',
    }
  );
}

async function start() {
  const typesPath = path.resolve('types/graphql-generated-types.ts');

  const typesContent = readFileSync(typesPath, 'utf8').replace(
    /export type Maybe<T> = T \| null/gm,
    'export type Maybe<T> = T | undefined'
  );

  writeOnFile({
    path: typesPath,
    content: typesContent,
  });
}

start().then().catch(console.error);
