import { writeFileSync, readFileSync } from 'fs';
import * as path from 'path';
import { Prisma } from '@prisma/client';
import { camelize } from '../../utils/string';

type IConfig = {
  outputPath: string;
  namespacePath: string;
  unwantedModels: ReadonlyArray<string>;
  inputSuffixes: ReadonlyArray<string>;
};

const config: IConfig = {
  namespacePath: 'node_modules/.prisma/client/index.d.ts',
  outputPath: 'server/services/database/entity-inputs/generated-inputs.ts',
  unwantedModels: [],
  inputSuffixes: ['CreateInput', 'WhereInput', 'UpdateInput', 'Select'],
};

function genTypes({
  models,
  suffix = '',
  prefix = '',
}: {
  models: string[];
  suffix?: string;
  prefix?: string;
}) {
  return Object.values(models).reduce(
    (acc, model) => ({
      ...acc,
      [camelize(model)]: `${prefix}${model}${suffix}`,
    }),
    {}
  );
}

function generateInputs(config: IConfig) {
  const models = Object.values(Prisma.ModelName).filter(
    model =>
      !config.unwantedModels
        .map(um => um.toLowerCase())
        .includes(model.toLowerCase())
  );

  const body = config.inputSuffixes
    .map(suffix =>
      `export type Generated${suffix}s = ${JSON.stringify(
        genTypes({ models, suffix, prefix: 'Prisma.' })
      )}`.replace(/\"/g, '')
    )
    .join('\n');

  return body;
}

function generateEntities(config: IConfig) {
  const models = Object.values(Prisma.ModelName);
  const prismaClientContentFile = readFileSync(
    path.resolve(config.namespacePath),
    { encoding: 'utf-8' }
  );
  const regex = new RegExp(
    `^export type (${models.join('|')}) = \{[^\}]*\}$`,
    'gm'
  );
  const entities = prismaClientContentFile.match(regex)?.join('\n\n');

  const res = `\n\nexport type GeneratedEntities = ${JSON.stringify(
    genTypes({ models })
  )}\n`.replace(/\"/g, '');

  return entities?.concat(res) ?? '';
}

/**
 * Generate Inputs for Prisma Models
 * @param config
 */
function start(config: IConfig) {
  const header = `
/** 
* THIS FILE IS GENERATED BY THE SCRIPT generate-inputs
* DO NOT EDIT THIS FILE DIRECTLY, ANY CHANGES WILL BE OVERWRITTEN
*
* @generated on ${new Date().toISOString()} 
* 
*/
  
import { Prisma } from '@prisma/client';\n\n`;

  const entities = generateEntities(config);
  const inputs = generateInputs(config);

  writeFileSync(
    path.resolve(config.outputPath),
    `${header}${entities}${inputs}`,
    {
      encoding: 'utf-8',
    }
  );
  console.info(
    'Generated Prisma Inputs successfully',
    `see: ${config.outputPath}`
  );
}

start(config);
